name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Run on pushes to the main branch
  pull_request: # Run on pull request events
  workflow_dispatch: # Allow manual triggers

concurrency:
  group: 'pages-${{ github.ref }}'
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - name: Prepare artifact
        run: |
          mkdir -p public
          cp index.html windsurf_logo_wordmark.png styles.css public/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public
  
  deploy-to-pages:
    needs: deploy
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
